<a href="https://colab.research.google.com/github/konicaRu/numpy-100/blob/master/Copy_of_100_Numpy_exercises_18_06_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.18.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a = np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a = np.zeros(10)
np.size(a)
a.itemsize

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
b = np.zeros(10)
b[4] = 1
print(b)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a = np.arange(10, 50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
c = np.nonzero([1,2,0,0,4,0])
print(c)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

Функция eye() возвращает двумерный массив у которого все элементы по диагонали равны 1, а все остальные равны 0.

Параметры:
N - целое число
Задает количество строк выходного массива.
M - целое число (необязательный)
Задает количество столбцов выходного массива. Если этот параметр не задан то M = N.
k - индекс диагонали (необязательный)
По умолчанию k = 0, что соответствует главной диагонали. Положительное значение k смещает диагональ вверх, отрицательное - вниз.
dtype - тип данных NumPy (необязательный)
Определяет тип данных выходного массива.
order - 'C' или 'F' (необязательный)
Этот параметр определяет в каком порядке массивы должны храниться в памяти: строчном C-стиле или столбчатом стиле Fortran.
Возвращает:
результат - массив NumPy
Массив размером (N, M) с единицами по указанной диагонали и остальными нулевыми элементами.

In [ ]:
np.eye(3,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.random((3,3))

array([[0.28659538, 0.16367424, 0.39655357],
       [0.97001585, 0.63831798, 0.47251308],
       [0.51401852, 0.70155427, 0.25431962]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a = np.random.random((10,10))
amin = a.min()
amax = a.max()
print(amin, amax)

0.0039132124544069 0.9958518477015249


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a = np.random.random(30)
amean = a.mean()
print(amean)

0.49500566922238604


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
A = np.ones((10, 15))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


https://pythonworld.ru/numpy/2.html https://pyprog.pro/index_section_iteration.html

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

http://espressocode.top/numpy-nan_to_num-in-python/

In [ ]:
print(0 * np.nan)
print(np.nan < np.inf)
print(np.nan == np. inf)
print(np.nan - np.inf)
print(np.nan in set ([np.nan]))
print(0.3 == 3*0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
a = np.diag(1+np.arange(4),k=0)
print(a)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
A = np.zeros((8, 8))
A[1::2, ::2] = 1
A[::2, 1::2] = 1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


A[1::2, ::2] первое значение строка, бежим строки начиная с первой до конца с шагом два. 
Второе значение меняем в строках 0 на 1 с шагом 2 

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.ones((6,7,8)))
print(np.unravel_index(99,(6,7,8)))

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
print(np.array([[0,1],[[1,0]]]), (4,4))

print(np.tile( np.array([[0,1],[1,0]]), (4,4)))


[list([0, 1]) list([[1, 0]])] (4, 4)
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


https://pyprog.pro/array_manipulation/tile.html
numpy.tile(a, rep)
Функция tile() создает массив повторением указанного массива a заданным количеством раз.
>>> a = np.array([1, 2])
>>> 
>>> np.tile(a, 2)
array([1, 2, 1, 2])
>>> 
>>> np.tile(a, [2, 2])
array([[1, 2, 1, 2],
       [1, 2, 1, 2]])
>>> 
>>> np.tile(a, [2, 2, 2])
array([[[1, 2, 1, 2],
        [1, 2, 1, 2]],

       [[1, 2, 1, 2],
        [1, 2, 1, 2]]])
>>> 

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
a = np.random.random((5,5))
print(a)
c = (a - np.mean (a)) / (np.std (a))
print(Z)

[[0.53996652 0.62903731 0.95975574 0.99651238 0.26190351]
 [0.83688979 0.20353085 0.04606009 0.77325797 0.20074   ]
 [0.58900536 0.5633814  0.74875577 0.27773472 0.2890488 ]
 [0.00546738 0.35701696 0.84445795 0.72235422 0.34362571]
 [0.71190117 0.70368264 0.37896704 0.49562688 0.94666779]]
[[ 0.85354909 -1.62786309  0.71820131 -1.10691733  1.71810203]
 [-0.9342986   0.85214473 -1.27862259  0.15897776  1.65792176]
 [-0.85710846  1.45042197 -0.64761014  0.09007899  0.33647227]
 [ 0.19310659 -1.3743374  -0.8540316   0.74624243  0.09974421]
 [ 1.23064734 -0.88605187 -1.2027099  -0.08801029  0.75195079]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
c = np.dot(a,b)
print(a)
print(b)
print(c)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import  *
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
a = np.arange(2, 6)
print(a)
print(a**a) 
print(a <- a)
print(1j * a)
print(a/1/1)
print(2<<a>>2)
print(a<a>a)

[2 3 4 5]
[   4   27  256 3125]
[False False False False]
[0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[2. 3. 4. 5.]
[ 2  4  8 16]


ValueError: ignored

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a = np.random.uniform(-10,+10,10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))

[-1.26881553  0.40706194  3.27824134 -2.05017365 -4.91061696  4.97088688
 -9.60626154  0.42957372 -5.84773384  5.77578248]
[ -2.   1.   4.  -3.  -5.   5. -10.   1.  -6.   6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.random.randint(0,10,10)
print(a)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[8 6 2 5 4 8 5 0 9 8]
[0 4 5 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="raise")
defaults = np.seterr(all="ignore")
a = np.ones(1)/0
print(a)
_ = np.seterr(**defaults)
a = np.ones(1)/0
print(a)
with np.errstate(all="ignore"):
    np.arange(3) / 0

FloatingPointError: ignored

https://numpy.org/doc/stable/reference/generated/numpy.seterr.html?highlight=seterr#numpy.seterr

Эта строка кода вызывает все ошибки с плавающей запятой:

np.seterr(all='raise')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(1) == np.emath.sqrt(1)

True

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(2)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,',', today,',', tomorrow)

2020-06-07 , 2020-06-09 , 2020-06-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
a = np.arange('2016-07', '2017-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31' '2016-08-01' '2016-08-02' '2016-08-03' '2016-08-04'
 '2016-08-05' '2016-08-06' '2016-08-07' '2016-08-08' '2016-08-09'
 '2016-08-10' '2016-08-11' '2016-08-12' '2016-08-13' '2016-08-14'
 '2016-08-15' '2016-08-16' '2016-08-17' '2016-08-18' '2016-08-19'
 '2016-08-20' '2016-08-21' '2016-08-22' '2016-08-23' '2016-08-24'
 '2016-08-25' '2016-08-26' '2016-08-27' '2016-08-28' '2016-08-29'
 '2016-08-30' '2016-08-31' '2016-09-01' '2016-09-02' '2016-09-03'
 '2016-09-04' '2016-09-05' '2016-09-06' '2016-09-07' '2016-09-08'
 '2016-09-09' '2016-09-10' '2016-09-11' '2016-09-12' '2016-09-13'
 '2016-09-

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A, B, C)
a_add = np.add(A,B,out=B)
print(a_add)

a_div = np.divide(A,2,out=A)
print(a_div)

a_negat = np.negative(A,out=A)
print(a_negat)

a_mult = np.multiply(A,B,out=A)
print(a_mult)

[1. 1. 1.] [2. 2. 2.] [3. 3. 3.]
[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
A = np.random.uniform(0,10,10)
print('creat_arraiv', A)
print(A%1) # остаток от деления
print(A - A%1)
print(A // 1) # делим нацело
print(np.floor(A))
print(A.astype(int))
print(np.trunc(A))

creat_arraiv [9.57007111 2.99562517 7.33743002 5.28079851 9.0446734  7.2150512
 6.65039099 8.21286963 7.71478453 0.50680742]
[0.57007111 0.99562517 0.33743002 0.28079851 0.0446734  0.2150512
 0.65039099 0.21286963 0.71478453 0.50680742]
[9. 2. 7. 5. 9. 7. 6. 8. 7. 0.]
[9. 2. 7. 5. 9. 7. 6. 8. 7. 0.]
[9. 2. 7. 5. 9. 7. 6. 8. 7. 0.]
[9 2 7 5 9 7 6 8 7 0]
[9. 2. 7. 5. 9. 7. 6. 8. 7. 0.]


numpy.trunc¶
numpy.trunc(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'trunc'>
Return the truncated value of the input, element-wise.

The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. In short, the fractional part of the signed number x is discarded.

DataFrame.astype() используется для приведения объекта pandas к указанному dtype. astype() также предоставляет возможность конвертировать любой подходящий существующий столбец в категориальный тип.

numpy.floor(x, *ufunc_args) = <ufunc 'floor'>
Функция floor() выполняет округление к меньшему целому числу. Данная функция часто называется пол числа x и обозначается как ⌊x⌋.

Параметры:
x - число или подобный массиву объект
Число или последовательность чисел.
*ufunc_args - аргументы универсальной функции
Аргументы, позволяющие настроить и оптимизировать работу функции (подробнее см. универсальные функции).
Возвращает:
результат - число или массив NumPy или его подкласс
Число или массив чисел, которые округлены к наименьшему целому числу.

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A = np.zeros((5,5))
A += np.arange(5)
B = np.arange(6)
print(B)
print(A)

[0 1 2 3 4 5]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
A = np.fromiter(generate(),dtype=float,count=-1)
B = np.arange(10, dtype=float)
print(A)
print(B)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**Yield** это ключевое слово, которое используется примерно как return — отличие в том, что функция вернёт генератор.
https://habr.com/ru/post/132554/

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
a = np.linspace(0,1,11)[1:-1]
b = np.random.randint(0, 10, 10)
print(a)
print(b)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[4 5 2 7 3 3 3 0 0 1]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
#a = np.random.randint(2, 85, 10)
a = np.random.random(10)
print(a)
a.sort()
print(a)

[0.77808627 0.08896448 0.55974158 0.55817212 0.84928186 0.57990259
 0.39565486 0.67083056 0.09759323 0.728561  ]
[0.08896448 0.09759323 0.39565486 0.55817212 0.55974158 0.57990259
 0.67083056 0.728561   0.77808627 0.84928186]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
a = np.arange(10)

print(np.add.reduce(a))


45


Reduces a’s dimension by one, by applying ufunc along one axis.

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.random(8)
B = np.random.random(10)
C = np.arange(10)
D = np.arange(10)
print(A, B)
print(A == B)
print(C == D)
print(np.array_equal(A, B))
print(np.array_equal(C, D))

[0.5405783  0.65315424 0.63855759 0.98467188 0.2468229  0.84534372
 0.11890651 0.70704171] [0.79292463 0.26254454 0.44380361 0.03158016 0.44623108 0.97446214
 0.99916496 0.28200171 0.76360366 0.40931771]
False
[ True  True  True  True  True  True  True  True  True  True]
False
True


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
a = np.zeros(10)
print(a)
a.flags.writeable = False
a[0] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
a = np.random.random((10, 2))
print(a)
X,Y = a[:,0], a[:,1]
print(X, Y)
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
#print(R)
#print(T)

#print(a)

[[0.07676217 0.45788626]
 [0.71985091 0.79571513]
 [0.85693925 0.00964634]
 [0.40957276 0.86076132]
 [0.22140003 0.70316406]
 [0.034229   0.52875509]
 [0.99174868 0.43787554]
 [0.07270207 0.04145399]
 [0.23694681 0.26846244]
 [0.61129299 0.91810146]]
[0.07676217 0.71985091 0.85693925 0.40957276 0.22140003 0.034229
 0.99174868 0.07270207 0.23694681 0.61129299] [0.45788626 0.79571513 0.00964634 0.86076132 0.70316406 0.52875509
 0.43787554 0.04145399 0.26846244 0.91810146]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a = np.random.random(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.11611193 0.91984048 0.5404784  0.94997457 0.88675399 0.78724914
 0.04415321 0.05367835 0.08951799 0.64956663]
[0.11611193 0.91984048 0.5404784  0.         0.88675399 0.78724914
 0.04415321 0.05367835 0.08951799 0.64956663]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
a = np.zeros((5,5), [('x',float),('y',float)])
print(a)
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)
print(np.linspace(0,11,10))

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
[ 0.          1.22222222  2.44444444  3.66666667  4.88888889  6.11111111
  7.33333333  8.55555556  9.77777778 11.        ]


numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
print(X)
Y = X + 0.5
print(Y)
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


Attributes
bitsint
The number of bits occupied by the type.

minint
Minimum value of given dtype.

maxint
Maximum value of given dtype.

класс numpy.iinfo (тип) [источник]
Машинные ограничения для целочисленных типов.

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html?highlight=set_printoptions#numpy.set_printoptions

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
a = np.arange(100)
#print(a)
b = np.random.uniform(0,100)
print(b)
print(np.abs(a-b))
index = (np.abs(a-b)).argmin()
print(a[index])

73.82438389971412
[73.8243839 72.8243839 71.8243839 70.8243839 69.8243839 68.8243839
 67.8243839 66.8243839 65.8243839 64.8243839 63.8243839 62.8243839
 61.8243839 60.8243839 59.8243839 58.8243839 57.8243839 56.8243839
 55.8243839 54.8243839 53.8243839 52.8243839 51.8243839 50.8243839
 49.8243839 48.8243839 47.8243839 46.8243839 45.8243839 44.8243839
 43.8243839 42.8243839 41.8243839 40.8243839 39.8243839 38.8243839
 37.8243839 36.8243839 35.8243839 34.8243839 33.8243839 32.8243839
 31.8243839 30.8243839 29.8243839 28.8243839 27.8243839 26.8243839
 25.8243839 24.8243839 23.8243839 22.8243839 21.8243839 20.8243839
 19.8243839 18.8243839 17.8243839 16.8243839 15.8243839 14.8243839
 13.8243839 12.8243839 11.8243839 10.8243839  9.8243839  8.8243839
  7.8243839  6.8243839  5.8243839  4.8243839  3.8243839  2.8243839
  1.8243839  0.8243839  0.1756161  1.1756161  2.1756161  3.1756161
  4.1756161  5.1756161  6.1756161  7.1756161  8.1756161  9.1756161
 10.1756161 11.1756161 12.1756161 13.1756161

Генерации числа с плавающей запятой — uniform() модуль random
random.uniform() используется для генерации числа с плавающей запятой в пределах заданного промежутка
Значение конечной точки может включаться в диапазон, но это не обязательно. Все зависит от округления значения числа с плавающей запятой;
Метод может, например, сгенерировать случайно вещественное число в промежутке между 10.5 и 25.5.

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
A = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
A = np.random.random((10,2))
print(A)
X,Y = np.atleast_2d(A[:,0], A[:,1]) # возвращает слайс из заданого дву мерного массива
print('_____________________________________________________')
print(X)
print(Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print('---------------------------------------------------')
print(D)

[[0.85057917 0.58612966]
 [0.78918444 0.45556765]
 [0.80777282 0.06914886]
 [0.98501862 0.03141653]
 [0.86698611 0.06691082]
 [0.56709058 0.97844457]
 [0.98525425 0.55753294]
 [0.77212559 0.19597467]
 [0.76652213 0.61555233]
 [0.19399949 0.03363423]]
_____________________________________________________
[[0.85057917 0.78918444 0.80777282 0.98501862 0.86698611 0.56709058
  0.98525425 0.77212559 0.76652213 0.19399949]]
[[0.58612966 0.45556765 0.06914886 0.03141653 0.06691082 0.97844457
  0.55753294 0.19597467 0.61555233 0.03363423]]
---------------------------------------------------
[[0.         0.14427665 0.51874996 0.57077195 0.519478   0.48402146
  0.1376777  0.39796467 0.08905773 0.85810727]
 [0.14427665 0.         0.38686561 0.46717791 0.39636755 0.56808974
  0.2209984  0.26015287 0.1615818  0.72957038]
 [0.51874996 0.38686561 0.         0.18121755 0.05925557 0.94060971
  0.5196332  0.13174031 0.54795836 0.61479996]
 [0.57077195 0.46717791 0.18121755 0.         0.12325387 1.0351453

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
A = (np.random.rand(10)*100).astype(np.float32)
print(A)
print('______________________________________')
Y = A.view(np.int32)
print(Y)
print('________________________________________')
Y[:] = A
print(Y)

[97.129745 21.382296  9.157343 26.064638 54.043896 62.443115 90.50801
 58.87695  24.27177  51.452995]
______________________________________
[1120027246 1101729521 1091732602 1104184417 1113074931 1115276736
 1119159322 1114341887 1103244438 1112395742]
________________________________________
[97 21  9 26 54 62 90 58 24 51]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
print(s)
print('______________________________________')
a = np.genfromtxt(s, delimiter=",", dtype=np.int )
print(a)

______________________________________
[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? Каков эквивалент перечисления для нумерующих массивов?(★★☆)

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)
print(a.shape)
print('_______________________________________')
for index, value in np.ndenumerate(a):
    print(index, value)
    print('________________________________________')
for index in np.ndindex(a.shape):
    print(index, a[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]] /n
(3, 3)
_______________________________________
(0, 0) 0
________________________________________
(0, 1) 1
________________________________________
(0, 2) 2
________________________________________
(1, 0) 3
________________________________________
(1, 1) 4
________________________________________
(1, 2) 5
________________________________________
(2, 0) 6
________________________________________
(2, 1) 7
________________________________________
(2, 2) 8
________________________________________
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


np.ndindex - N-мерный объект итератора для индексации массивов.

Учитывая форму массива, экземпляр ndindex выполняет итерацию по N-мерному индексу массива. На каждой итерации возвращается кортеж индексов, последнее измерение повторяется первым.

np.ndenumerate - Итератор многомерного индекса.
Возвращает итератор, дающий пары координат и значений массива.

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print(np.linspace(-1,1,10))
print('__________________________________')
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
__________________________________
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81

**numpy.linspace** Вернуть равномерно распределенные числа за указанный интервал.

Возвращает num равномерно распределенных выборок, рассчитанных по интервалу [start, stop].

Конечная точка интервала может быть дополнительно исключена.(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),5)
print(a)

[[0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) Вычитать среднее значение каждой строки матрицы

In [ ]:
X = np.random.rand(5, 10)
print(X, '\n'  '________________________________'  '\n')

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y, '\n'  '________________________________'  '\n')



[[0.26520366 0.50700436 0.77600583 0.11423663 0.13005759 0.33657211
  0.67255039 0.04269745 0.42456044 0.80528843]
 [0.22684683 0.66201423 0.78499446 0.31185073 0.37163223 0.31187339
  0.83473191 0.65535038 0.45752828 0.08421073]
 [0.25127647 0.82314027 0.2058998  0.6762776  0.73022873 0.67843404
  0.42340549 0.73322726 0.83019848 0.39628517]
 [0.76240404 0.76265756 0.51033309 0.66126831 0.38782193 0.58728275
  0.29767153 0.99522667 0.44881517 0.52416188]
 [0.69259287 0.39117414 0.44082997 0.22142001 0.9569662  0.12678961
  0.10935264 0.03990688 0.27512741 0.37772868]] 
________________________________

[[-0.14221403  0.09958667  0.36858814 -0.29318106 -0.2773601  -0.07084558
   0.2651327  -0.36472024  0.01714275  0.39787074]
 [-0.24325649  0.19191092  0.31489114 -0.15825259 -0.09847109 -0.15822993
   0.36462859  0.18524706 -0.01257504 -0.38589258]
 [-0.32356086  0.24830294 -0.36893753  0.10144027  0.1553914   0.10359671
  -0.15143184  0.15838993  0.25536115 -0.17855217]
 [ 0.16863975 

https://pyprog.pro/statistics_functions/mean.html

#### 59. How to sort an array by the nth column? (★★☆) Как отсортировать массив по n-ой колонке?

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z, '\n'  '________________________________'  '\n')
print(Z[:,1], '\n'  '________________________________'  '\n')
print(Z[Z[:,1].argsort()])

[[5 7 7]
 [9 2 6]
 [5 2 0]] 
________________________________

[7 2 2] 
________________________________

[[9 2 6]
 [5 2 0]
 [5 7 7]]



https://pyprog.pro/sort/argsort.html

#### 60. How to tell if a given 2D array has null columns? (★★☆) Как определить, имеет ли заданный 2D массив нулевые столбцы?

In [ ]:
Z = np.random.randint(0,3,(3,10))
print(Z , '\n'  '________________________________'  '\n')
print((~Z.any(axis=0)).any())

[[0 1 0 2 2 0 2 0 2 2]
 [0 1 0 0 0 1 0 1 0 2]
 [0 0 2 2 0 2 2 0 1 0]] 
________________________________

True


#### 61. Find the nearest value from a given value in an array (★★☆) Найти ближайшее значение из заданного значения в массиве

In [ ]:
Z = np.random.uniform(0,1,10)
print(Z , '\n'  '________________________________'  '\n')
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m, '\n'  '________________________________'  '\n')
print(np.abs(Z - z).argmin())

[0.61631481 0.30017582 0.68064013 0.88202955 0.055441   0.21920285
 0.47692752 0.34279637 0.20667898 0.98729446] 
________________________________

0.4769275209480761 
________________________________

6


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) Рассматривая два массива в форме (1,3) и (3,1), как вычислить их сумму с помощью итератора?

In [ ]:
A = np.arange(3).reshape(3,1)
print(A, '\n'  '________________________________'  '\n')
B = np.arange(3).reshape(1,3)
print(B  , '\n'  '________________________________'  '\n')
it = np.nditer([A,B,None])
print(it , '\n'  '________________________________'  '\n')
for x,y,z in it: z[...] = x + y
print(it.operands[2] , '\n'  '________________________________'  '\n')

# пример работы итератора
a = np.arange(6).reshape(2,3)
print(a , '\n'  '________________________________'  '\n')
for x in np.nditer(a):
    print(x, end=' ')


[[0]
 [1]
 [2]] 
________________________________

[[0 1 2]] 
________________________________

________________________________

[[0 1 2]
 [1 2 3]
 [2 3 4]] 
________________________________

[[0 1 2]
 [3 4 5]] 
________________________________

0 1 2 3 4 5 

#### 63. Create an array class that has a name attribute (★★☆) Создать класс массива с атрибутом имени

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z)
print (Z.name)

[0 1 2 3 4 5 6 7 8 9]
range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) Рассмотрим заданный вектор, как добавить по 1 к каждому элементу, индексируемому по второму вектору (будьте осторожны с повторяющимися индексами).

In [ ]:
Z = np.ones(10)
print(Z , '\n'  '________________________________'  '\n')
I = np.random.randint(0,len(Z),20)
print(I , '\n'  '________________________________'  '\n')
Z += np.bincount(I, minlength=len(Z))
print( Z , '\n'  '________________________________'  '\n')

np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
________________________________

[3 2 3 1 2 3 4 3 0 4 6 9 4 3 1 8 4 8 9 5] 
________________________________

[2. 3. 3. 6. 5. 2. 2. 1. 3. 3.] 
________________________________

[ 3.  5.  5. 11.  9.  3.  3.  1.  5.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) Как аккумулировать элементы вектора (X) в массив (F) на основе индексного списка (I)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


https://pyprog.pro/statistics_functions/bincount.html

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)  Рассматривая (w,h,3) изображение (dtype=ubyte), вычислите количество уникальных цветов

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#print(I)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
print(F)
n = len(np.unique(F))
print(np.unique(I))

[[257   1 257 256   1   1 257   1 256   1 257 257 256 256   0 257]
 [  0   1 257 257   1   1   0 257 257 257   1 256 256 257   0 256]
 [  0   0 257   1   0   1 257 256 257   1   0   1   0   0 256 256]
 [257 256   0 257 256   0 256 257 257   1   0 257 257 257   1   0]
 [256   0 257 256 257 256   0 256   1   0 257 257 257   1   0   0]
 [  1   0 257   0   1 256   0 257 256 257   1   0   1   1 257 256]
 [  0 257 257   0   1   1 256   0   0 257 257   1 257   0 257   0]
 [  0   1   0   0   1   0 257 256 257 257 257   0 257 256 257 256]
 [  1 257   1   0 256 257   0 256   1   0   0 257   1 257   1   1]
 [  1   0 256   1   0   0   0 256 256   0 257 257   0   1   1   1]
 [  1 256 257   1   1 257   1   0   1   0   0   1 257 256   0 257]
 [  1   1   1   1 256   1 257   0   1   1 257   0   0   0   1 257]
 [257   1   0 256   0   0   0 257 256   0   0   1 256   1   0 256]
 [257 257   0   0   0   1   0   0 256   1 256 257   1   1   1   1]
 [256 256   1 256 256 257   1 257 256 256 256   1 256   0   1 

https://numpy.org/doc/stable/reference/generated/numpy.unique.html?highlight=unique#numpy.unique

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)  Учитывая четырехмерный массив, как получить сумму сразу по двум последним осям?

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
print(A , '\n'  '________________________________'  '\n')
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum , '\n'  '________________________________'  '\n')
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[3 1 6 1]
   [3 2 6 8]
   [8 1 2 3]]

  [[1 7 3 8]
   [5 8 9 4]
   [9 2 7 2]]

  [[4 4 5 9]
   [6 2 4 0]
   [4 2 2 2]]

  [[4 3 2 3]
   [1 4 7 7]
   [0 1 8 3]]]


 [[[4 7 9 4]
   [1 6 6 0]
   [4 7 6 3]]

  [[9 0 5 8]
   [8 6 6 4]
   [3 8 3 9]]

  [[5 2 5 4]
   [9 0 8 9]
   [7 7 5 6]]

  [[8 9 2 0]
   [6 3 1 4]
   [0 8 6 5]]]


 [[[8 9 3 3]
   [4 0 9 1]
   [1 4 5 2]]

  [[4 7 0 6]
   [4 3 9 1]
   [2 2 4 9]]

  [[6 2 7 6]
   [5 4 2 2]
   [4 1 8 0]]

  [[7 8 7 9]
   [6 7 1 8]
   [7 3 4 5]]]] 
________________________________

[[44 65 44 43]
 [57 69 67 52]
 [49 51 47 72]] 
________________________________

[[44 65 44 43]
 [57 69 67 52]
 [49 51 47 72]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
# bincount - Подсчитывать количество вхождений каждого значения в массиве неотрицательных ints.
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.39219532 0.46540321 0.45826853 0.55581942 0.53215349 0.47143338
 0.64223339 0.48271384 0.50020738 0.4839034 ]
0    0.392195
1    0.465403
2    0.458269
3    0.555819
4    0.532153
5    0.471433
6    0.642233
7    0.482714
8    0.500207
9    0.483903
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) Как получить диагональ точечного продукта?

In [ ]:
A = np.random.uniform(0,1,(5,5))
print(A , '\n'  '________________________________'  '\n')
B = np.random.uniform(0,1,(5,5))
print(B , '\n'  '________________________________'  '\n')

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

[[0.43700888 0.93426526 0.45537171 0.32271619 0.55637673]
 [0.82121256 0.21802558 0.76581636 0.36989675 0.44165862]
 [0.10797781 0.31892428 0.32312331 0.53368866 0.93575872]
 [0.83898258 0.75048212 0.94284587 0.49329538 0.88982403]
 [0.27973827 0.09320838 0.15288989 0.38026604 0.4536526 ]] 
________________________________

[[0.83160451 0.47614165 0.16349716 0.42591791 0.04195718]
 [0.62673457 0.13603288 0.4170149  0.79164853 0.25903012]
 [0.75109683 0.66522676 0.25936702 0.53175661 0.33940117]
 [0.95742157 0.46774273 0.16628794 0.6021811  0.96133696]
 [0.67399267 0.73656012 0.73628987 0.14156676 0.27112637]] 
________________________________



array([1.9749524 , 1.42843833, 1.01219342, 1.87584294, 0.5763328 ])

https://pyprog.pro/linear_algebra_functions/dot.html

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)  Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, перемежающимися между каждым значением?

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
Z0[::nz+1] = Z
print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)  Рассмотрим массив размерности (5,5,3), как его умножить на массив с размерами (5,5)

In [ ]:
A = np.ones((5,5,3))
print(A , '\n'  '________________________________'  '\n')
B = 2*np.ones((5,5))
print(B , '\n'  '________________________________'  '\n')
B1 = np.ones((5,5))
print(B1 , '\n'  '________________________________'  '\n')
print(B[:,:,None] , '\n'  'slice________________________________'  '\n')
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] 
________________________________

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]] 
________________________________

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
________________________________

[[[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]] 
slice________________________________

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 

#### 72. How to swap two rows of an array? (★★★) Как поменять местами два ряда массива?

In [ ]:
A = np.arange(25).reshape(5,5)
print(A , '\n'  '________________________________'  '\n')
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
________________________________

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) Рассмотрим набор из 10 треугольников, описывающих 10 треугольников (с общими вершинами), найдем набор уникальных отрезков линий, составляющих все треугольники

In [ ]:
faces = np.random.randint(0,100,(10,3))
print(faces, '\n'  '________________________________'  '\n') 
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print(F , '\n'  'np.roll________________________________'  '\n')
F = F.reshape(len(F)*3,2)
print(F , '\n'  'F.reshape________________________________'  '\n')
F = np.sort(F,axis=1)
print(F , '\n'  'F = np.sort(F,axis=1) ________________________________'  '\n')
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print('result', '\n', G)

[[43 28 65]
 [70 19 24]
 [38 71 89]
 [48 40 99]
 [56 92 86]
 [89 31 67]
 [92 95 96]
 [42 12 20]
 [76 59 75]
 [21 49 42]] 
________________________________

[[43 28 28 65 65 43]
 [70 19 19 24 24 70]
 [38 71 71 89 89 38]
 [48 40 40 99 99 48]
 [56 92 92 86 86 56]
 [89 31 31 67 67 89]
 [92 95 95 96 96 92]
 [42 12 12 20 20 42]
 [76 59 59 75 75 76]
 [21 49 49 42 42 21]] 
np.roll________________________________

[[43 28]
 [28 65]
 [65 43]
 [70 19]
 [19 24]
 [24 70]
 [38 71]
 [71 89]
 [89 38]
 [48 40]
 [40 99]
 [99 48]
 [56 92]
 [92 86]
 [86 56]
 [89 31]
 [31 67]
 [67 89]
 [92 95]
 [95 96]
 [96 92]
 [42 12]
 [12 20]
 [20 42]
 [76 59]
 [59 75]
 [75 76]
 [21 49]
 [49 42]
 [42 21]] 
F.reshape________________________________

[[28 43]
 [28 65]
 [43 65]
 [19 70]
 [19 24]
 [24 70]
 [38 71]
 [71 89]
 [38 89]
 [40 48]
 [40 99]
 [48 99]
 [56 92]
 [86 92]
 [56 86]
 [31 89]
 [31 67]
 [67 89]
 [92 95]
 [95 96]
 [92 96]
 [12 42]
 [12 20]
 [20 42]
 [59 76]
 [59 75]
 [75 76]
 [21 49]
 [42 49]
 [21 42]] 
F = 

сдвиг элементов по заданной оси 
numpy.roll(a, shift, axis=None)[source]
Roll array elements along a given axis.

Elements that roll beyond the last position are re-introduced at the first.

Parameters
aarray_like
Input array.

shiftint or tuple of ints
The number of places by which elements are shifted. If a tuple, then axis must be a tuple of the same size, and each of the given axes is shifted by the corresponding number. If an int while axis is a tuple of ints, then the same value is used for all given axes.

axisint or tuple of ints, optional
Axis or axes along which elements are shifted. By default, the array is flattened before shifting, after which the original shape is restored.

Returns
resndarray
Output array, with the same shape as a.

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) Учитывая массив C, который является bincount, как создать массив A, который np.bincount(A) == C?

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C , '\n'  '________________________________'  '\n')
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1] 
________________________________

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
Как вычислить средние значения с помощью скользящего окна по массиву?


In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★) 
Рассмотрим одномерный массив Z, построим двумерный массив, первая строка которого (Z[0],Z[1],Z[2]) и каждая последующая строка будет сдвинута на 1 (последняя строка должна быть (Z[-3],Z[-2],Z[-1])

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    print(shape, '\n' 'shape' '________________________________'  '\n')
    strides = (a.itemsize, a.itemsize)
    print(strides, '\n' 'strides' '________________________________'  '\n')
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
Z1 = np.arange(10), 3
print(Z1 , '\n'  '________________________________'  '\n')
print(Z)

(8, 3) 
shape________________________________

(8, 8) 
strides________________________________

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 3) 
________________________________

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
Как отменить логическое значение или изменить знак float на месте?

In [ ]:
Z = np.random.uniform(-10,10,100)
print(Z , '\n'  '________________________________'  '\n')
Z1 = np.logical_not(Z, out=Z)
print(Z1)

Z = np.random.uniform(-10,10,100)
#print(Z , '\n'  '________________________________'  '\n')
np.negative(Z, out=Z)

[-2.17778502e-01 -7.60926686e+00 -9.68865187e+00  2.04581807e+00
  2.29492834e+00 -5.56615543e+00  8.94365492e+00  6.23097013e-03
  2.69876074e+00 -6.86324972e+00  5.96859579e+00 -1.82612965e+00
 -3.10793529e+00 -2.09846791e+00  7.06326979e+00  6.28856939e+00
 -1.90300520e+00  5.99716337e+00  9.92405013e+00  4.63037207e+00
  1.75646100e+00  6.85941604e+00  9.55789026e+00  7.18085036e+00
 -8.09388484e+00  1.58819875e+00  2.09420040e+00  2.87805628e+00
 -8.24275985e+00  2.45586119e+00  5.34637192e+00  3.49889027e+00
  9.13017664e+00  2.71970942e-01 -2.10042311e+00 -4.53230935e+00
  5.52782953e-01  9.11546164e+00 -9.30553115e+00  5.29937522e+00
 -6.78194480e+00 -5.35960966e+00 -7.28912240e+00 -5.66214470e+00
  9.21240187e-01 -7.80830316e+00  4.67664924e+00  9.95969312e+00
 -2.63680739e+00 -4.23358234e+00 -7.83422339e+00 -8.32899181e+00
  7.41419377e+00 -3.79605489e+00 -9.90891774e+00 -2.29519572e+00
 -6.16304833e+00  8.72300354e+00 -5.60124719e+00 -5.94459792e+00
 -6.69769240e+00 -6.23258

array([ 9.14222786, -0.18088375,  2.00539308, -4.97339119, -0.20633657,
       -6.39621117,  8.33538099, -0.75715736,  2.56935184, -2.80598819,
       -9.36963569,  3.02518241, -6.17102828,  8.13243277,  6.09853308,
        7.21050408, -6.08518375,  2.52864638,  9.55023478, -2.95647853,
       -2.05361629, -8.19375681, -8.77477464,  4.28036982, -3.99102047,
       -6.58439956, -4.64424902, -9.09159486, -4.56198461, -6.42379124,
        4.4531651 , -0.18835889,  3.73034872,  3.13966379,  6.38987821,
       -8.31456385, -6.03787387, -5.67794426,  1.30190892,  8.83770765,
        1.82179136,  2.58607501,  4.15153061,  5.73685175,  0.51218836,
        8.50235404,  1.92372997, -7.89966297,  6.25869478,  4.44549062,
        6.7113121 , -2.99948078,  4.16690771,  8.64564033, -4.42420902,
       -2.7637634 ,  1.43190259,  8.96011084,  7.57267448,  9.65645635,
        9.93823206, -0.2141567 , -8.89638836,  7.80538257,  0.07081977,
       -0.33768123, -1.56986401,  9.28674208, -3.79421988,  1.86

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
Рассмотрим 2 набора точек P0, P1, описывающих линии (2d), и точку p, как вычислить расстояние от p до каждой линии i (P0 [i], P1 [i])?

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    print(T , '\n'  'T ________________________________'  '\n')
    L = (T**2).sum(axis=1)
    print(L , '\n'  'L ________________________________'  '\n')
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    print(U , '\n'  'U ________________________________'  '\n')
    U = U.reshape(len(U),1)
    print(U , '\n'  'U_resh ________________________________'  '\n')
    D = P0 + U*T - p
    print(D , '\n'  'D ________________________________'  '\n')
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
print(P0 , '\n'  'P0 ________________________________'  '\n')
P1 = np.random.uniform(-10,10,(10,2))
print(P1 , '\n'  'P1 ________________________________'  '\n')
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[[ 8.56256836 -4.91601161]
 [ 2.38072263 -7.50240285]
 [-3.97266609  7.79693011]
 [ 2.99726781  8.25124486]
 [ 0.30293157  4.61012253]
 [ 8.14409039 -8.07434473]
 [-8.6224277  -7.38517223]
 [ 6.17185433 -2.01184683]
 [ 1.27306244 -7.12857265]
 [ 6.38685878  4.4443035 ]] 
P0 ________________________________

[[ 2.83626569  1.55780376]
 [-7.11668854  0.19543158]
 [ 3.58287449 -3.84279802]
 [-9.24013048  0.95839942]
 [ 5.33984213 -0.84322442]
 [-9.64053593  1.43411116]
 [-2.0862791  -6.04404409]
 [ 2.02977913 -0.92393833]
 [ 6.48882711 -9.46015164]
 [-0.48871255  5.43685293]] 
P1 ________________________________

[[ -5.72630268   6.47381536]
 [ -9.49741117   7.69783443]
 [  7.55554058 -11.63972814]
 [-12.2373983   -7.29284544]
 [  5.03691056  -5.45334695]
 [-17.78462633   9.50845589]
 [  6.5361486    1.34112814]
 [ -4.1420752    1.0879085 ]
 [  5.21576467  -2.33157899]
 [ -6.87557133   0.99254942]] 
T ________________________________

[ 74.70082768 149.45747394 192.56946458 202.9395117   

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
**Рассмотрим 2 набора точек P0, P1, описывающих линии (2d), и набор точек P, как вычислить расстояние от каждой точки j (P [j]) до каждой линии i (P0 [i], P1 [i])**

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.36873197  1.39331349 15.8120616   3.49614407  0.43669246 10.24713291
   8.73040675  0.97432345  1.12826811  7.43819202]
 [ 0.79833589  1.34573907 14.66977322  1.99170645  0.70872119  9.82815067
   7.59562284  2.21778873  0.73398989  5.8402016 ]
 [ 2.50912597  9.14831536 11.60105941  2.42882165  3.75568254  3.24335646
  15.34944954  4.53411777  5.93248199  8.64657072]
 [11.4458207  10.53657806  0.44259468 11.22081543 14.93763213  2.12506606
   6.78835059 16.44162044 11.09417444  5.30462019]
 [ 1.1663932   0.67666906 16.06912493  2.65962548  0.68654909 11.7737518
   6.15156872  0.9632077   2.68816976  5.93516715]
 [10.5473592   2.97188668  5.32085827  9.18289996 10.07555228  5.01157891
   1.05356251 12.13447366  3.91802046  5.43405301]
 [ 0.73186271  7.4959736  10.1084557   0.43505637  5.25841524  3.79054713
  11.70059005  6.36429527  5.32332573  5.13497822]
 [ 1.70168492  4.78916745 13.42589493  2.32742424  1.94271511  6.96581406
  11.12095304  3.12043988  2.16669451  7.22903976]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
Рассмотрим произвольный массив, напишите функцию, которая извлекает часть с фиксированной формой и центрируется на данном элементе (заполнение при необходимости значением заполнения)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 0 6 3 1 9 9 7 9 7]
 [4 7 0 2 8 1 4 5 8 9]
 [9 2 4 3 6 7 8 8 6 6]
 [3 3 2 2 1 6 9 5 7 0]
 [4 8 7 7 8 5 6 6 9 0]
 [8 2 9 4 0 2 7 4 2 5]
 [5 5 4 8 0 5 9 5 8 0]
 [2 9 9 4 3 8 6 9 0 1]
 [3 8 5 9 9 0 2 8 4 7]
 [0 3 8 2 0 5 4 2 8 2]]
[[0 0 0 0 0]
 [0 0 0 6 3]
 [0 4 7 0 2]
 [0 9 2 4 3]
 [0 3 3 2 2]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


https://numpy.org/doc/stable/reference/generated/numpy.maximum.html?highlight=maximum#numpy.maximum
Поэлементный максимум элементов массива.
np.maximum
Сравните два массива и возвращает новый массив, содержащий поэлементные максимумы. Если один из сравниваемых элементов является NaN, то этот элемент возвращается. Если оба элемента являются NaN, то возвращается первый. Последнее различие важно для сложных NaN, которые определены как по крайней мере одна из действительных или мнимых частей, являющихся NaN. Чистый эффект состоит в том, что NaN распространяются.

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
print(Z , '\n'  '________________________________'  '\n')
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
________________________________

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


https://numpy.org/doc/stable/reference/generated/numpy.lib.stride_tricks.as_strided.html?highlight=lib%20stride_tricks%20as_strided#numpy.lib.stride_tricks.as_strided

#### 82. Compute a matrix rank (★★★)
Вычислить матричный ранг

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
print(U,  '\n'  '________________________________'  '\n', S,  '\n'  '________________________________'  '\n', V)
rank = np.sum(S > 1e-10)
print(rank)

[[-0.22163341 -0.47377386  0.02838485  0.03690002 -0.64622789  0.02522884
  -0.0798107   0.12948308  0.13032633 -0.51563756]
 [-0.23520997 -0.10265553 -0.1508296  -0.06316806 -0.09617254  0.69145875
   0.0163293   0.46831095 -0.1962015   0.40243901]
 [-0.30187618  0.16502048  0.86390381 -0.22891229  0.12546158  0.20601066
   0.05881159 -0.01152948  0.04084833 -0.13952446]
 [-0.41928829  0.286109   -0.40589856 -0.45756484  0.09057373  0.06603068
   0.07683834 -0.06831681  0.5723182  -0.13242606]
 [-0.3452761  -0.40074314 -0.05725167 -0.45549169  0.05299888 -0.186004
  -0.2741883  -0.42112158 -0.40214458  0.24039484]
 [-0.3967153   0.10208443  0.04522568  0.46231701 -0.33667877 -0.02553793
   0.38703683 -0.43657948  0.10225191  0.38929934]
 [-0.3639323  -0.43588381 -0.02779537  0.23279813  0.53727314 -0.28087793
   0.36472176  0.3385751   0.03877731 -0.07666462]
 [-0.25564371  0.48708223 -0.07704579 -0.13358535 -0.26681441 -0.42063112
   0.1655401   0.36938268 -0.50215094 -0.0974319 ]
 [

http://www.mathprofi.ru/rang_matricy.html

#### 83. How to find the most frequent value in an array?
Как найти наиболее частое значение в массиве?

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[2 0 7 2 7 4 5 4 9 8 5 5 0 3 7 2 7 8 0 8 5 1 7 9 9 6 1 4 6 5 9 4 9 7 7 0 3
 4 9 7 9 5 2 0 0 3 0 1 7 2]
7


np.bincount --- https://numpy.org/doc/stable/reference/generated/numpy.bincount.html?highlight=bincount#numpy.bincount

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
Извлеките все смежные блоки 3x3 из случайной матрицы 10x10

In [ ]:
Z = np.random.randint(0,5,(10,10))
print(Z , '\n'  '________________________________'  '\n')
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[1 1 4 0 0 3 0 1 4 1]
 [3 1 0 3 2 3 1 0 3 1]
 [1 2 4 3 0 0 2 4 1 0]
 [3 0 2 0 0 2 3 1 3 0]
 [0 2 0 0 2 1 3 4 3 4]
 [3 1 4 4 3 3 4 4 0 2]
 [4 3 3 3 4 4 2 4 0 2]
 [0 4 1 2 2 2 2 0 0 0]
 [1 4 3 2 2 0 4 1 3 4]
 [2 1 0 3 1 2 0 3 4 0]] 
________________________________

[[[[1 1 4]
   [3 1 0]
   [1 2 4]]

  [[1 4 0]
   [1 0 3]
   [2 4 3]]

  [[4 0 0]
   [0 3 2]
   [4 3 0]]

  [[0 0 3]
   [3 2 3]
   [3 0 0]]

  [[0 3 0]
   [2 3 1]
   [0 0 2]]

  [[3 0 1]
   [3 1 0]
   [0 2 4]]

  [[0 1 4]
   [1 0 3]
   [2 4 1]]

  [[1 4 1]
   [0 3 1]
   [4 1 0]]]


 [[[3 1 0]
   [1 2 4]
   [3 0 2]]

  [[1 0 3]
   [2 4 3]
   [0 2 0]]

  [[0 3 2]
   [4 3 0]
   [2 0 0]]

  [[3 2 3]
   [3 0 0]
   [0 0 2]]

  [[2 3 1]
   [0 0 2]
   [0 2 3]]

  [[3 1 0]
   [0 2 4]
   [2 3 1]]

  [[1 0 3]
   [2 4 1]
   [3 1 3]]

  [[0 3 1]
   [4 1 0]
   [1 3 0]]]


 [[[1 2 4]
   [3 0 2]
   [0 2 0]]

  [[2 4 3]
   [0 2 0]
   [2 0 0]]

  [[4 3 0]
   [2 0 0]
   [0 0 2]]

  [[3 0 0]
   [0 0 2]
   [0 2 1]]

  [[0 0 2]
   [0 2 3]
   [2 1 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
Создайте подкласс 2D-массива так, чтобы Z [i, j] == Z [j, i]

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  7 14 12  8]
 [ 7  1  5 10  8]
 [14  5  5 42 15]
 [12 10 42  4  4]
 [ 8  8 15  4  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
Рассмотрим набор p матриц, имеющих форму (n, n), и набор p векторов с формой (n, 1). Как вычислить сумму продуктов матрицы p за один раз? (результат имеет форму (n, 1))

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


np.tensordot -- https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html?highlight=tensordot#numpy.tensordot

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
Рассмотрим массив 16x16, как получить сумму блоков (размер блока 4x4)

In [ ]:
Z = np.ones((16,16))
print(Z , '\n'  '________________________________'  '\n')
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 
________________________________

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)
Как реализовать Game of Life, используя массивы?

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


https://ru.wikipedia.org/wiki/Игра_«Жизнь»#Компьютерная_реализация

#### 89. How to get the n largest values of an array (★★★)
Как получить n самых больших значений массива

In [ ]:
Z = np.arange(10000)
print(Z , '\n'  '________________________________'  '\n')
np.random.shuffle(Z)
print(Z , '\n'  '________________________________'  '\n')
n = 5
print (Z[np.argsort(Z)[-n:]] , '\n'  '________________________________'  '\n')
print(np.argsort(Z)[-n:] , '\n'  '________________________________'  '\n')
print (Z[np.argpartition(-Z,n)[:n]])

[   0    1    2 ... 9997 9998 9999] 
________________________________

[5302 4671 8642 ... 7446 6625 5322] 
________________________________

[9995 9996 9997 9998 9999] 
________________________________

[1463 5241 6921 6116  750] 
________________________________

[9999 9998 9997 9996 9995]


np.argsort --- https://numpy.org/doc/stable/reference/generated/numpy.argsort.html?highlight=argsort#numpy.argsort

numpy.random.shuffle --- https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html?highlight=random%20shuffle#numpy.random.shuffle

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
Учитывая произвольное количество векторов, построить декартово произведение (каждую комбинацию каждого элемента)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)
Как создать массив записей из обычного массива

In [3]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z , '\n'  '________________________________'  '\n')
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']] 
________________________________

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


numpy.core.records.fromarrays ------
numpy.core.records.fromarrays(arrayList, dtype=None, shape=None, formats=None, names=None, titles=None, aligned=False, byteorder=None)[source]


create a record array from a (flat) list of arrays

>>>
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])
(2, 'dd', 2.0) # may vary
x1[1]=34
r.a
array([1, 2, 3, 4])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
Рассмотрим большой вектор Z, вычислим Z до степени 3, используя 3 разных метода

In [12]:
x = np.random.rand(5, 2)
print(x , '\n'  '________________________________'  '\n')

print(np.power(x,3),  '\n'  '________________________________'  '\n')
print(x*x*x , '\n'  '________________________________'  '\n')
print(np.einsum('i,i,i->i',x,x,x) , '\n'  '________________________________'  '\n')

[[0.41632907 0.74557782]
 [0.07843936 0.4850298 ]
 [0.90269639 0.65841466]
 [0.66239404 0.3298604 ]
 [0.00894506 0.23889943]] 
________________________________

[[7.21622741e-02 4.14456480e-01]
 [4.82616515e-04 1.14105152e-01]
 [7.35571867e-01 2.85429247e-01]
 [2.90635892e-01 3.58914104e-02]
 [7.15731816e-07 1.36346921e-02]] 
________________________________

[[7.21622741e-02 4.14456480e-01]
 [4.82616515e-04 1.14105152e-01]
 [7.35571867e-01 2.85429247e-01]
 [2.90635892e-01 3.58914104e-02]
 [7.15731816e-07 1.36346921e-02]] 
________________________________



ValueError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [16]:
A = np.random.randint(0,5,(8,3))
print(A , '\n'  '________________________________'  '\n')

B = np.random.randint(0,5,(2,2))
print(B , '\n'  '________________________________'  '\n')

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)



[[0 3 3]
 [1 3 4]
 [1 1 3]
 [0 3 4]
 [1 2 2]
 [3 4 1]
 [4 0 4]
 [3 2 4]] 
________________________________

[[4 2]
 [3 4]] 
________________________________

[1 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
Рассматривая матрицу 10х3, извлеките строки с неравными значениями (например [2,2,3])

In [25]:
Z = np.random.randint(0,5,(10,3))
print(Z , '\n'  '________________________________'  '\n')
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1) # all - Проверьте, все ли элементы массива вдоль заданной оси оцениваются в True
print(E , '\n'  '________________________________'  '\n')
U = Z[~E]
print(U , '\n'  '________________________________'  '\n')
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 1]
 [3 1 0]
 [2 3 0]
 [0 1 3]
 [4 4 1]
 [4 0 4]
 [0 1 1]
 [0 0 2]
 [3 0 2]
 [1 2 4]] 
________________________________

[ True False False False False False False False False False] 
________________________________

[[3 1 0]
 [2 3 0]
 [0 1 3]
 [4 4 1]
 [4 0 4]
 [0 1 1]
 [0 0 2]
 [3 0 2]
 [1 2 4]] 
________________________________

[[3 1 0]
 [2 3 0]
 [0 1 3]
 [4 4 1]
 [4 0 4]
 [0 1 1]
 [0 0 2]
 [3 0 2]
 [1 2 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)
Преобразование вектора интов в матричное двоичное представление

In [33]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
print(I , '\n'  '________________________________'  '\n')
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(((I.reshape(-1,1) & (2**np.arange(8))) ) , '\n'  '________________________________'  '\n')
print((2**np.arange(8)) , '\n'  '2**np.arange(8)________________________________'  '\n')
print(I.reshape(-1,1) , '\n'  'reshape________________________________'  '\n')
print(B , '\n'  '________________________________'  '\n')
print(B[:,::-1])

[  0   1   2   3  15  16  32  64 128] 
________________________________

[[  0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0   0]
 [  1   2   0   0   0   0   0   0]
 [  1   2   4   8   0   0   0   0]
 [  0   0   0   0  16   0   0   0]
 [  0   0   0   0   0  32   0   0]
 [  0   0   0   0   0   0  64   0]
 [  0   0   0   0   0   0   0 128]] 
________________________________

[  1   2   4   8  16  32  64 128] 
2**np.arange(8)________________________________

[[  0]
 [  1]
 [  2]
 [  3]
 [ 15]
 [ 16]
 [ 32]
 [ 64]
 [128]] 
reshape________________________________

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]] 
________________________________

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [36]:
Z = np.random.randint(0,2,(6,3))
print(Z , '\n'  '________________________________'  '\n')
A = np.unique(Z, axis=0)
print(A)

[[0 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]] 
________________________________

[0 1]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [44]:
X = np.random.randn(10) 
print(X , '\n' ,X.size, '\n'  '________________________________'  '\n')
N = 10 # number of bootstrap samples
a = np.random.randint(0, X.size, (N, X.size))
print(a , '\n'  '________________________________'  '\n')
means = X[a].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[ 0.73094182 -0.01957284  0.5105177  -1.76728327 -1.26599956 -0.21757776
 -0.85290045 -1.10005214  0.33544027 -0.32758729] 
 10 
________________________________

[[2 7 7 9 5 6 1 4 0 1]
 [8 8 8 3 4 6 6 1 7 2]
 [5 9 8 2 4 4 3 5 8 1]
 [9 7 4 6 7 4 3 5 9 7]
 [4 9 5 5 9 7 2 2 2 3]
 [4 6 8 2 4 4 3 5 5 9]
 [0 8 7 7 0 0 5 5 5 2]
 [6 3 7 6 1 3 4 8 2 9]
 [5 4 4 6 7 8 6 3 6 4]
 [3 4 0 0 7 4 3 0 7 4]] 
________________________________

[-0.92758349 -0.06798095]
